@GeniusSquare.WebAPI_HostAddress = https://localhost:7259

@configId=default
@pieceId=J4
@orientationId=bl

GET {{GeniusSquare.WebAPI_HostAddress}}/config/{{configId}}

###

GET {{GeniusSquare.WebAPI_HostAddress}}/pieces

###

GET {{GeniusSquare.WebAPI_HostAddress}}/pieces/{{pieceId}}

###

GET {{GeniusSquare.WebAPI_HostAddress}}/pieces/{{pieceId}}/{{orientationId}}

###
